
### check status
GET http://localhost:8083/connectors/jdbc_source_mysql_01/status HTTP/1.1
Content-Type: application/json
Accept: application/json

### connector
POST http://localhost:8083/connectors HTTP/1.1
Content-Type: application/json
Accept: application/json

{ 
    "name": "jdbc_source_mysql_01",
     "config": {
            "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
            "connection.url": "jdbc:mysql://mysql:3306/connect_test",
            "connection.user": "confluent",
            "connection.password": "confluent",
            "topic.prefix": "mysql-01-",
            "poll.interval.ms" : 3600000,
            "table.whitelist" : "test.accounts",
            "mode":"bulk",
            "transforms":"createKey,extractInt",
            "transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
            "transforms.createKey.fields":"id",
            "transforms.extractInt.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
            "transforms.extractInt.field":"id"
        }
     }
}

