version: "3.9"
services: 

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks: 
      - default
    ports: 
      - "2181:2181"
  
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    networks: 
      - default
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
networks: 
  default: