version: "3.9"
services: 

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports: 
      - "2181:2181"
  
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  kafka_admin:
    build: 
      context: ./kafka-admin
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        target: /home/node/app/node_modules
      - type: bind
        source: ./kafka-admin
        target: /home/node/app
    environment: 
      KAFKA_SERVER: kafka:9092